language: python
python:
  - "2.6"
  - "2.7"
  - "3.2" 
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jre-headless ant
script: cd py4j-java && python --version && cd ../py4j-python && nosetests -w src -c nose.cfg
